### ISSUE TITLE
More licenses

### ISSUE THREAD

**Issue by troy0820** [captainsafia/legit#1]
#### I don't know how far you want to go with this, but github has a lot of licenses stuffed in this repo.
[github licenses](https://github.com/github/choosealicense.com/tree/gh-pages/_licenses)

#### I wasn't gonna make an issue for each one, but I can definitely for and add the text we need to cover all of 'em. 👍 

- [x] agpl3	
- [x] apache2	
- [x] mit	
- [x] bsd-2-clause
- [x] bsd-3-clause
- [x] epl-1.0
- [x] gpl-2.0
- [x] gpl-3.0	
- [x] lgpl-2.1
- [x] lgpl-3.0
- [x] unlicense

**Comment by pmonks** [comment]
Might be worth taking a look at the forks referenced from issue #14.  It sidesteps this whole issue by pulling license texts at runtime from a comprehensive registry (i.e. the [SPDX license list](http://spdx.org/licenses)).  That seems to us to be more scalable than manually replicating individual license texts here.

(and yes @maoo and I are trying to get this in PR form as soon as we can - we're a bit hampered by only having an hour or two of overlap in our respective timezones)

**Comment by troy0820** [comment]
What we can do, because the endpoints don't cover all these licenses, I can close this issue and allow the documentation to describe the licenses it does support.  👍 Keep up the good work.
