### ISSUE TITLE
When passing arguments, if username is not passed, and a year is, the year will be used as the username.

### ISSUE THREAD

**Issue by ridhahassoun** [captainsafia/legit#17]
Title is self-explanatory.
`legit put mit 2017` results in the license reading as `Copyright (c) 2017 2017`.

**Comment by pmonks** [comment]
FWIW [our PR](https://github.com/captainsafia/legit/pull/15) fixes this by using [key=value pairs on the command line](https://github.com/captainsafia/legit/pull/15/files#diff-04c6e90faac2675aa89e2176d2eec7d8R31), instead of positional parameters (which are brittle).

**Comment by ridhahassoun** [comment]
v3.0.0 fixes this by using flags.
