### ISSUE TITLE
Request: set default user

### ISSUE THREAD

**Issue by ghost** [captainsafia/legit#22]
Oi, thanks for legit, it's awesome!

So here is my request, i would like to set my user, currently legit uses the logged-in windows user, in my case it is "jerom", because windows 10. Since i'm lazy i don't want to add the user all the time, so i thought about something like ``legit set user jerome724``. 

Would that be possible? 

Bye ♥

**Comment by yeskunall** [comment]
I second this. I also would like the option of setting the [user] the same as the one in my global `.gitconfig`.

**Comment by mischah** [comment]
I think this would be solved with https://github.com/captainsafia/legit/issues/25 😘
